# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Revolving Design
tagline:          'A developer blog'
description:      'Notes to my future-self'
url:              http://iancwill.com
baseurl:          /

author:
  name:           'Ian Will'
  url:            https://twitter.com/ian_cw

paginate:         2

# Custom vars
version:          2.1.0

github_username:  iancw
twitter_username: ian_cw

gems: [jekyll-paginate]
