# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Revolving Design
tagline:          'A Jekyll theme'
description:      'Just some thoughts about software and random notes to my future-self'
url:              http://iancwill.com
baseurl:          /

author:
  name:           'Ian Will'
  url:            https://twitter.com/ian_cw

paginate:         2

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/iancw/iancw.github.io
  me:             https://github.com/iancw/

twitter:
  me:             https://twitter.com/ian_cw

gems: [jekyll-paginate]
